import numpy as np
from gloabal_connections import fetch_data
from truedata_ws.websocket.TD import TD
import pandas as pd
import pandas_ta as ta
from datetime import datetime, timedelta,date
# import talib as ta
import threading
import multiprocessing
import warnings
warnings.filterwarnings("ignore")


username = ''
password = ''
realtime_port = 8082

td_app = TD(username, password, live_port=None)



def get_live_data(alias,bar_size,start_time,end_time):
    req_ids = td_app.get_historic_data(alias, bar_size=bar_size, start_time=start_time, end_time=end_time)
    df = pd.DataFrame(req_ids)
    return df

def generate_data(symbol,start_time,end_time):
    try:
        data = get_live_data(symbol,'eod',start_time,end_time)
        data = data.head(data.shape[0] -1)
        min_data = td_app.get_historic_data(symbol,end_time=end_time,bar_size='5 mins')
        df = pd.DataFrame(min_data)
        new_df = df.loc[df['time']==end_time]
        new_df['v'] = df['v'].sum()
        data = data.append(new_df)
        weekly_close = get_live_data(symbol,'week',start_time,end_time+timedelta(days=1))
        monthly_close = get_live_data(symbol,'month',start_time,end_time+timedelta(days=1))


        latest_sma = ta.sma(data['v'],length =15)
        bb_period = 20
        bb_std = 2.0
        latest_upper_bollinger_band = ta.bbands(data["c"], length=bb_period,std=bb_std)
        latest_upper_bollinger_band = latest_upper_bollinger_band[latest_upper_bollinger_band.columns[2]]

        weekly_upper_bollinger_band = ta.bbands(weekly_close["c"], length=bb_period,std=bb_std)
        weekly_upper_bollinger_band = weekly_upper_bollinger_band[weekly_upper_bollinger_band.columns[2]]
        monthly_upper_bollinger_band= ta.bbands(monthly_close["c"], length=bb_period,std=bb_std)
        monthly_upper_bollinger_band = monthly_upper_bollinger_band[monthly_upper_bollinger_band.columns[2]]
        weekly_upper_bollinger_band.drop(weekly_upper_bollinger_band.index[-1], inplace=True)
        latest_rsi = ta.rsi(data["c"], length=14)
        weekly_rsi = ta.rsi(weekly_close["c"], length=14)
        monthly_rsi = ta.rsi(monthly_close["c"], length=14)


        monthly_wma_close_30 = monthly_close["c"].ewm(span=30).mean()
        monthly_wma_close_50 = monthly_close["c"].ewm(span=50).mean()
        monthly_close['Pivot'] = (monthly_close['h'] + monthly_close['l'] + monthly_close['c'])/3
        monthly_close['R1'] = 2*monthly_close['Pivot'] - monthly_close['l']
        monthly_close['R1'] = monthly_close['R1'].shift(1)
        monthly_close['Pivot'] = monthly_close['Pivot'].shift(1)

        # print (weekly_close)

        new_dataframe = pd.DataFrame(columns=["daily_close","daily_high","weekly_close","monthly_close","latest_sma","latest_upper_bollinger_band","weekly_upper_bollinger_band","monthly_upper_bollinger_band","latest_rsi","weekly_rsi","monthly_rsi","monthly_wma_close_30","monthly_wma_close_50"])
        new_dataframe.loc[0] =  data['c'].iloc[-1],data['h'].iloc[-1],weekly_close['c'].iloc[-1],monthly_close['c'].iloc[-1],latest_sma.iloc[-1],latest_upper_bollinger_band.iloc[-1],weekly_upper_bollinger_band.iloc[-1],monthly_upper_bollinger_band.iloc[-1],latest_rsi.iloc[-1],weekly_rsi.iloc[-1],monthly_rsi.iloc[-1],monthly_wma_close_30.iloc[-1],monthly_wma_close_50.iloc[-1]

        

        data_latest = data_latest[['time','o','h','l','c','symbol','v']]
        main_df = pd.concat([data_latest,new_dataframe],axis=1)
      
        btst_result = [
            (main_df["v"][0] > main_df["latest_sma"][0]) &
            (main_df["c"][0] > main_df["latest_upper_bollinger_band"][0]) &
            (main_df["weekly_close"][0] > main_df["weekly_upper_bollinger_band"][0]) &
            (main_df["monthly_close"][0] > main_df["monthly_upper_bollinger_band"][0]) &
            (main_df["latest_rsi"][0] > 60) &
            (main_df["weekly_rsi"][0] > 60) &
            (main_df["monthly_rsi"][0] > 60) &
            (main_df["monthly_wma_close_30"][0] > main_df["monthly_wma_close_50"][0]) &
            (main_df['high_for_r1_condition'][0]<=main_df['r1_upper_range'][0])&
            (main_df['high_for_r1_condition'][0]>=main_df['r1_lower_range'][0])&
            (
                (((main_df['high_for_r1_condition'][0]-main_df['close_for_r1_condition'][0])/main_df['high_for_r1_condition'][0])*100)< main_df['close_percent'][0]
            )
        ]
        print (symbol,start_time,end_time)
        if btst_result[0]==True:
            print(data_latest)
            data_latest.to_csv('newcheck5.csv', mode='a', index=False, header=False)

    except Exception as e:
        print (e)


# start_time = datetime(2020, 12, 1, 9, 0, 0)
# end_time = datetime(2022, 12, 13, 16, 0, 0)

def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]


def process_start(dates,symbol_data2):

    for symbol in symbol_data2:
        for end_time in dates:
            end_time = datetime.combine(end_time, datetime(year=2023,month=2,day=1,hour = 15,minute=15,second=0).time())
            # end_time = end_time+ timedelta(hours = 15,minutes=15,seconds=00)
            start_time = end_time-timedelta(days=3*365)
            generate_data(symbol,start_time,end_time)



# symbol_data = [i[0] for i in fetch_data(f"select distinct(alias) from symbol_data where stock_exchange = 'nse' and alive = 1 and type='EQ' and `index` = 0 and symbol not like '%-I%'")]
# datelist = [i[0] for i in fetch_data("select date from daily_nifty  WHERE MONTH(date) in ('01','02','03','04','05','06','07','08','09','10','11','12') AND YEAR(date) in ('2021','2022','2023');")]
symbol_data = ["20MICRONS","21STCENMGM","360ONE","3IINFOLTD","3MINDIA","3PLAND","4THDIM","5PAISA","63MOONS","A2ZINFRA","AAATECH","AAKASH","AAREYDRUGS","AARON","AARTIDRUGS","AARTIIND","AARTIPHARM","AARTISURF","AARVEEDEN","AARVI","AAVAS","ABAN","ABB","ABBOTINDIA","ABCAPITAL","ABFRL","ABMINTLLTD","ABSLAMC","ACC","ACCELYA","ACCURACY","ACE","ACEINTEG","ACI","ADANIENT","ADANIGREEN","ADANIPORTS","ADANIPOWER","ADANITRANS","ADFFOODS","ADL","ADORWELD","ADROITINFO","ADSL","ADVANIHOTR","ADVENZYMES","AEGISCHEM","AETHER","AFFLE","AGARIND","AGI","AGRITECH","AGROPHOS","AGSTRA","AHL","AHLADA","AHLEAST","AHLUCONT","AIAENG","AIRAN","AIROLAM","AJANTPHARM","AJMERA","AJOONI","AKASH","AKG","AKI","AKSHAR","AKSHARCHEM","AKSHOPTFBR","AKZOINDIA","ALANKIT","ALBERTDAVD","ALEMBICLTD","ALICON","ALKALI","ALKEM","ALKYLAMINE","ALLCARGO","ALLSEC","ALMONDZ","ALOKINDS","ALPA","ALPHAGEO","ALPSINDUS","AMARAJABAT","AMBER","AMBICAAGAR","AMBIKCO","AMBUJACEM","AMDIND","AMIORG","AMJLAND","AMRUTANJAN","ANANDRATHI","ANANTRAJ","ANDHRAPAP","ANDHRSUGAR","ANDREWYU","ANGELONE","ANIKINDS","ANKITMETAL","ANMOL","ANTGRAPHIC","ANUP","ANURAS","APARINDS","APCL","APCOTEXIND","APEX","APLAPOLLO","APLLTD","APOLLO","APOLLOHOSP","APOLLOPIPE","APOLLOTYRE","APOLSINHOT","APTECHT","APTUS","ARCHIDPLY","ARCHIES","ARENTERP","ARIES","ARIHANTCAP","ARIHANTSUP","ARMANFIN","AROGRANITE","ARROWGREEN","ARSHIYA","ARTEMISMED","ARTNIRMAN","ARVEE","ARVIND","ARVINDFASN","ARVSMART","ASAHIINDIA","ASAHISONG","ASAL","ASALCBR","ASHAPURMIN","ASHIANA","ASHIMASYN","ASHOKA","ASHOKLEY","ASIANENE","ASIANHOTNR","ASIANPAINT","ASIANTILES","ASMS","ASPINWALL","ASTEC","ASTERDM","ASTRAL","ASTRAMICRO","ASTRAZEN","ASTRON","ATFL","ATGL","ATLANTA","ATUL","ATULAUTO","AUBANK","AURIONPRO","AUROPHARMA","AURUM","AUSOMENT","AUTOAXLES","AUTOIND","AVADHSUGAR","AVALON","AVANTIFEED","AVONMORE","AVROIND","AVTNPL","AWHCL","AWL","AXISBANK","AXISCADES","AXITA","AYMSYNTEX","BAFNAPH","BAGFILMS","BAIDFIN","BAJAJ-AUTO","BAJAJCON","BAJAJELEC","BAJAJFINSV","BAJAJHCARE","BAJAJHIND","BAJAJHLDNG","BAJFINANCE","BALAJITELE","BALAMINES","BALAXI","BALKRISHNA","BALKRISIND","BALLARPUR","BALMLAWRIE","BALPHARMA","BALRAMCHIN","BANARBEADS","BANARISUG","BANCOINDIA","BANDHANBNK","BANG","BANKA","BANKBARODA","BANKINDIA","BANSWRAS","BARBEQUE","BASF","BASML","BATAINDIA","BAYERCROP","BBL","BBOX","BBTC","BBTCL","BCG","BCLIND","BCONCEPTS","BCP","BDL","BEARDSELL","BECTORFOOD","BEDMUTHA","BEL","BEML","BEPL","BERGEPAINT","BESTAGRO","BFINVEST","BFUTILITIE","BGRENERGY","BHAGCHEM","BHAGERIA","BHAGYANGR","BHANDARI","BHARATFORG","BHARATGEAR","BHARATRAS","BHARATWIRE","BHARTIARTL","BHEL","BIGBLOC","BIKAJI","BIL","BINANIIND","BINDALAGRO","BIOCON","BIOFILCHEM","BIRLACABLE","BIRLACORPN","BIRLAMONEY","BLAL","BLBLIMITED","BLISSGVS","BLKASHYAP","BLS","BLUECOAST","BLUEDART","BLUESTARCO","BODALCHEM","BOHRAIND","BOMDYEING","BOROLTD","BORORENEW","BOSCHLTD","BPCL","BPL","BRIGADE","BRITANNIA","BRNL","BROOKS","BSE","BSHSL","BSL","BSOFT","BTML","BURNPUR","BUTTERFLY","BVCL","BYKE","CALSOFT","CAMLINFINE","CAMPUS","CAMS","CANBK","CANFINHOME","CANTABIL","CAPACITE","CAPLIPOINT","CAPTRUST","CARBORUNIV","CAREERP","CARERATING","CARTRADE","CARYSIL","CASTROLIND","CCCL","CCHHL","CCL","CDSL","CEATLTD","CELEBRITY","CENTENKA","CENTEXT","CENTRALBK","CENTRUM","CENTUM","CENTURYPLY","CENTURYTEX","CERA","CEREBRAINT","CESC","CGCL","CGPOWER","CHALET","CHAMBLFERT","CHEMBOND","CHEMCON","CHEMFAB","CHEMPLASTS","CHENNPETRO","CHEVIOT","CHOICEIN","CHOLAFIN","CHOLAHLDNG","CIGNITITEC","CINELINE","CINEVISTA","CIPLA","CLEAN","CLEDUCATE","CLSEL","CMICABLES","CMSINFO","COALINDIA","COASTCORP","COCHINSHIP","COFFEEDAY","COFORGE","COLPAL","COMPINFO","COMPUSOFT","CONCOR","CONFIPET","CONSOFINVT","CONTROLPR","CORALFINAC","CORDSCABLE","COROMANDEL","COSMOFIRST","COUNCODOS","CRAFTSMAN","CREATIVE","CREATIVEYE","CREDITACC","CREST","CRISIL","CROMPTON","CROWN","CSBBANK","CSLFINANCE","CTE","CUB","CUBEXTUB","CUMMINSIND","CUPID","CYBERMEDIA","CYBERTECH","CYIENT","DAAWAT","DABUR","DALBHARAT","DALMIASUG","DAMODARIND","DANGEE","DATAMATICS","DATAPATTNS","DBCORP","DBL","DBOL","DBREALTY","DBSTOCKBRO","DCAL","DCBBANK","DCI","DCM","DCMFINSERV","DCMNVL","DCMSHRIRAM","DCMSRIND","DCW","DCXINDIA","DECCANCE","DEEPAKFERT","DEEPAKNTR","DEEPENR","DEEPINDS","DELHIVERY","DELPHIFX","DELTACORP","DELTAMAGNT","DEN","DENORA","DEVIT","DEVYANI","DGCONTENT","DHAMPURSUG","DHANBANK","DHANI","DHANUKA","DHARMAJ","DHARSUGAR","DHRUV","DHUNINV","DIAMONDYD","DICIND","DIGISPICE","DIGJAMLMTD","DIL","DISHTV","DIVGIITTS","DIVISLAB","DIXON","DJML","DLF","DLINKINDIA","DMART","DMCC","DNAMEDIA","DODLA","DOLATALGO","DOLLAR","DONEAR","DPABHUSHAN","DPSCLTD","DPWIRES","DRCSYSTEMS","DREAMFOLKS","DREDGECORP","DRREDDY","DSSL","DTIL","DUCON","DVL","DWARKESH","DYCL","DYNAMATECH","DYNPRO","E2E","EASEMYTRIP","EASTSILK","ECLERX","EDELWEISS","EDUCOMP","EICHERMOT","EIDPARRY","EIFFL","EIHAHOTELS","EIHOTEL","EIMCOELECO","EKC","ELDEHSG","ELECON","ELECTCAST","ELECTHERM","ELGIEQUIP","ELGIRUBCO","ELIN","EMAMILTD","EMAMIPAP","EMAMIREAL","EMIL","EMKAY","EMMBI","EMUDHRA","ENDURANCE","ENERGYDEV","ENGINERSIN","ENIL","EPL","EQUITASBNK","ERIS","EROSMEDIA","ESABINDIA","ESCORTS","ESSARSHPNG","ESSENTIA","ESTER","ETHOSLTD","EUROTEXIND","EVEREADY","EVERESTIND","EXCEL","EXCELINDUS","EXIDEIND","EXPLEOSOL","EXXARO","FACT","FAIRCHEMOR","FAZE3Q","FCL","FCONSUMER","FCSSOFT","FDC","FEDERALBNK","FIBERWEB","FIEMIND","FILATEX","FINCABLES","FINEORG","FINOPB","FINPIPE","FIVESTAR","FLEXITUFF","FLFL","FLUOROCHEM","FMGOETZE","FMNL","FOCUS","FOODSIN","FORCEMOT","FORTIS","FOSECOIND","FSL","FUSION","GABRIEL","GAEL","GAIL","GAL","GALAXYSURF","GALLANTT","GANDHITUBE","GANECOS","GANESHBE","GANESHHOUC","GANGAFORGE","GANGESSECU","GARFIBRES","GATEWAY","GATI","GAYAHWS","GEECEE","GEEKAYWIRE","GENCON","GENESYS","GENUSPAPER","GENUSPOWER","GEOJITFSL","GEPIL","GESHIP","GET&D","GFLLIMITED","GHCL","GICHSGFIN","GICRE","GILLANDERS","GILLETTE","GINNIFILA","GIPCL","GISOLUTION","GKWLIMITED","GLAND","GLAXO","GLENMARK","GLFL","GLOBAL","GLOBALVECT","GLOBE","GLOBUSSPR","GLS","GMBREW","GMDCLTD","GMMPFAUDLR","GMRINFRA","GMRP&UI","GNA","GNFC","GOACARBON","GOCLCORP","GOCOLORS","GODFRYPHLP","GODHA","GODREJAGRO","GODREJCP","GODREJIND","GODREJPROP","GOKEX","GOKUL","GOKULAGRO","GOLDIAM","GOLDTECH","GOODLUCK","GOODYEAR","GOYALALUM","GPIL","GPPL","GPTINFRA","GRANULES","GRAPHITE","GRASIM","GRAUWEIL","GRAVITA","GREAVESCOT","GREENLAM","GREENPANEL","GREENPLY","GREENPOWER","GRINDWELL","GRINFRA","GRMOVER","GROBTEA","GRPLTD","GRSE","GRWRHITECH","GSCLCEMENT","GSFC","GSLSU","GSPL","GSS","GTL","GTLINFRA","GTPL","GUFICBIO","GUJALKALI","GUJAPOLLO","GUJGASLTD","GUJRAFFIA","GULFOILLUB","GULFPETRO","GULPOLY","GVKPIL","HAL","HAPPSTMNDS","HARDWYN","HARIOMPIPE","HARRMALAYA","HARSHA","HATHWAY","HATSUN","HAVELLS","HAVISHA","HBLPOWER","HBSL","HCC","HCG","HCL-INSYS","HCLTECH","HDFC","HDFCAMC","HDFCBANK","HDFCLIFE","HEADSUP","HECPROJECT","HEG","HEIDELBERG","HEMIPROP","HERANBA","HERCULES","HERITGFOOD","HEROMOTOCO","HESTERBIO","HEUBACHIND","HEXATRADEX","HFCL","HGINFRA","HGS","HIKAL","HIL","HILTON","HIMATSEIDE","HINDALCO","HINDCOMPOS","HINDCON","HINDCOPPER","HINDMOTORS","HINDOILEXP","HINDPETRO","HINDUNILVR","HINDWAREAP","HINDZINC","HIRECT","HISARMETAL","HITECH","HITECHCORP","HITECHGEAR","HLEGLAS","HLVLTD","HMT","HMVL","HNDFDS","HOMEFIRST","HONAUT","HONDAPOWER","HOVS","HPAL","HPIL","HPL","HSCL","HTMEDIA","HUBTOWN","HUDCO","HUHTAMAKI","HYBRIDFIN","IBREALEST","IBULHSGFIN","ICDSLTD","ICEMAKE","ICICIBANK","ICICIGI","ICICIPRULI","ICIL","ICRA","IDBI","IDEA","IDFC","IDFCFIRSTB","IEL","IEX","IFBAGRO","IFBIND","IFCI","IFGLEXPOR","IGARASHI","IGL","IGPL","IIFL","IIFLSEC","IITL","IL&FSENGG","IL&FSTRANS","IMAGICAA","IMFA","IMPAL","IMPEXFERRO","INCREDIBLE","INDBANK","INDHOTEL","INDIACEM","INDIAGLYCO","INDIAMART","INDIANB","INDIANCARD","INDIANHUME","INDIGO","INDIGOPNTS","INDNIPPON","INDOAMIN","INDOBORAX","INDOCO","INDORAMA","INDOSTAR","INDOTECH","INDOTHAI","INDOWIND","INDRAMEDCO","INDSWFTLAB","INDSWFTLTD","INDTERRAIN","INDUSINDBK","INDUSTOWER","INFIBEAM","INFOBEAN","INFOMEDIA","INFY","INGERRAND","INOXGREEN","INOXWIND","INSECTICID","INSPIRISYS","INTELLECT","INTENTECH","INTLCONV","INVENTURE","IOB","IOC","IOLCP","IONEXCHANG","IPCALAB","IPL","IRB","IRCON","IRCTC","IRFC","IRIS","IRISDOREME","ISEC","ISFT","ISGEC","ISMTLTD","ITC","ITDC","ITDCEM","ITI","IVC","IVP","IWEL","IZMO","J&KBANK","JAGRAN","JAGSNPHARM","JAIBALAJI","JAICORPLTD","JAIPURKURT","JAMNAAUTO","JASH","JAYAGROGN","JAYBARMARU","JAYNECOIND","JAYSREETEA","JBCHEPHARM","JBMA","JCHAC","JETAIRWAYS","JETFREIGHT","JHS","JINDALPHOT","JINDALPOLY","JINDALSAW","JINDALSTEL","JINDRILL","JINDWORLD","JISLDVREQS","JISLJALEQS","JITFINFRA","JKCEMENT","JKIL","JKLAKSHMI","JKPAPER","JKTYRE","JMA","JMFINANCIL","JOCIL","JPASSOCIAT","JPOLYINVST","JPPOWER","JSL","JSWENERGY","JSWHL","JSWISPL","JSWSTEEL","JTEKTINDIA","JTLIND","JUBLFOOD","JUBLINDS","JUBLINGREA","JUBLPHARMA","JUSTDIAL","JWL","JYOTHYLAB","JYOTISTRUC","KABRAEXTRU","KAJARIACER","KAKATCEM","KALPATPOWR","KALYANI","KALYANIFRG","KALYANKJIL","KAMATHOTEL","KAMDHENU","KAMOPAINTS","KANANIIND","KANORICHEM","KANPRPLA","KANSAINER","KAPSTON","KARMAENG","KARURVYSYA","KAUSHALYA","KAVVERITEL","KAYA","KAYNES","KBCGLOBAL","KCP","KCPSUGIND","KDDL","KEC","KECL","KEEPLEARN","KEI","KELLTONTEC","KENNAMET","KERNEX","KESORAMIND","KEYFINSERV","KFINTECH","KHADIM","KHAICHEM","KHAITANLTD","KHANDSE","KICL","KILITCH","KIMS","KINGFA","KIOCL","KIRIINDUS","KIRLFER","KIRLOSBROS","KIRLOSENG","KIRLOSIND","KITEX","KKCL","KMSUGAR","KNRCON","KOHINOOR","KOKUYOCMLN","KOLTEPATIL","KOPRAN","KOTAKBANK","KOTARISUG","KOTHARIPET","KOTHARIPRO","KOVAI","KPIGREEN","KPITTECH","KPRMILL","KRBL","KREBSBIO","KRIDHANINF","KRISHANA","KRITI","KRITIKA","KRITINUT","KRSNAA","KSB","KSCL","KSHITIJPOL","KSL","KSOLVES","KTKBANK","KUANTUM","L&TFH","LAGNAM","LAKPRE","LAL","LALPATHLAB","LAMBODHARA","LANCER","LANDMARK","LAOPALA","LASA","LATENTVIEW","LAURUSLABS","LAXMICOT","LAXMIMACH","LCCINFOTEC","LEMONTREE","LEXUS","LFIC","LGBBROSLTD","LGBFORGE","LIBAS","LIBERTSHOE","LICHSGFIN","LICI","LIKHITHA","LINC","LINCOLN","LINDEINDIA","LODHA","LOKESHMACH","LOTUSEYE","LOVABLE","LOYALTEX","LPDC","LSIL","LT","LTIM","LTTS","LUMAXIND","LUMAXTECH","LUPIN","LUXIND","LXCHEM","LYKALABS","LYPSAGEMS","M&M","M&MFIN","MAANALU","MACPOWER","MADHAV","MADHUCON","MADRASFERT","MAGADSUGAR","MAGNUM","MAHABANK","MAHAPEXLTD","MAHASTEEL","MAHEPC","MAHESHWARI","MAHINDCIE","MAHLIFE","MAHLOG","MAHSCOOTER","MAHSEAMLES","MAITHANALL","MALLCOM","MALUPAPER","MANAKALUCO","MANAKCOAT","MANAKSIA","MANAKSTEEL","MANALIPETC","MANAPPURAM","MANGALAM","MANGCHEFER","MANGLMCEM","MANINDS","MANINFRA","MANOMAY","MANORAMA","MANORG","MANUGRAPH","MANYAVAR","MAPMYINDIA","MARALOVER","MARATHON","MARICO","MARINE","MARKSANS","MARSHALL","MARUTI","MASFIN","MASKINVEST","MASTEK","MATRIMONY","MAWANASUG","MAXHEALTH","MAXIND","MAXVIL","MAYURUNIQ","MAZDA","MAZDOCK","MBAPL","MBLINFRA","MCDOWELL-N","MCL","MCLEODRUSS","MCX","MEDANTA","MEDICAMEQ","MEDICO","MEDPLUS","MEGASOFT","MEGASTAR","MELSTAR","MENONBE","MEP","METALFORGE","METROBRAND","METROPOLIS","MFL","MFSL","MGEL","MGL","MHLXMIRU","MHRIL","MICEL","MIDHANI","MINDACORP","MINDTECK","MIRCELECTR","MIRZAINT","MITCON","MITTAL","MMFL","MMP","MMTC","MODIRUBBER","MODISONLTD","MOHITIND","MOIL","MOKSH","MOL","MOLDTECH","MOLDTKPAC","MONARCH","MONTECARLO","MORARJEE","MOREPENLAB","MOTHERSON","MOTILALOFS","MOTOGENFIN","MPHASIS","MPSLTD","MRF","MRO-TEK","MRPL","MSPL","MSTCLTD","MSUMI","MTARTECH","MTEDUCARE","MTNL","MUKANDLTD","MUKTAARTS","MUNJALAU","MUNJALSHOW","MURUDCERA","MUTHOOTCAP","MUTHOOTFIN","NACLIND","NAGAFERT","NAGREEKCAP","NAGREEKEXP","NAHARCAP","NAHARINDUS","NAHARPOLY","NAHARSPING","NAM-INDIA","NARMADA","NATCOPHARM","NATHBIOGEN","NATIONALUM","NATNLSTEEL","NAUKRI","NAVA","NAVINFLUOR","NAVKARCORP","NAVNETEDUL","NAZARA","NBCC","NBIFIN","NCC","NCLIND","NDGL","NDL","NDRAUTO","NDTV","NECCLTD","NECLIFE","NELCAST","NELCO","NEOGEN","NESCO","NESTLEIND","NETWORK18","NEULANDLAB","NEWGEN","NEXTMEDIA","NFL","NGIL","NGLFINE","NH","NHPC","NIACL","NIBL","NIITLTD","NILAINFRA","NILASPACES","NILKAMAL","NINSYS","NIPPOBATRY","NIRAJ","NIRAJISPAT","NITCO","NITINSPIN","NITIRAJ","NKIND","NLCINDIA","NMDC","NOCIL","NOIDATOLL","NORBTEAEXP","NOVARTIND","NRAIL","NRBBEARING","NRL","NSIL","NSLNISP","NTPC","NUCLEUS","NURECA","NUVOCO","NXTDIGITAL","NYKAA","OAL","OBCL","OBEROIRLTY","OCCL","OFSS","OIL","OILCOUNTUB","OLECTRA","OMAXAUTO","OMAXE","OMINFRAL","ONELIFECAP","ONEPOINT","ONGC","ONMOBILE","ONWARDTEC","OPTIEMUS","ORBTEXP","ORCHPHARMA","ORICONENT","ORIENTABRA","ORIENTALTL","ORIENTBELL","ORIENTCEM","ORIENTELEC","ORIENTHOT","ORIENTLTD","ORIENTPPR","ORISSAMINE","ORTEL","ORTINLAB","OSIAHYPER","OSWALAGRO","OSWALSEEDS","PAGEIND","PAISALO","PALASHSECU","PALREDTEC","PANACEABIO","PANACHE","PANAMAPET","PANSARI","PAR","PARACABLES","PARADEEP","PARAGMILK","PARAS","PARASPETRO","PARSVNATH","PASUPTAC","PATANJALI","PATELENG","PATINTLOG","PAYTM","PCBL","PCJEWELLER","PDMJEPAPER","PDSL","PEARLPOLY","PEL","PENIND","PENINLAND","PERSISTENT","PETRONET","PFC","PFIZER","PFOCUS","PFS","PGEL","PGHH","PGHL","PGIL","PHOENIXLTD","PIDILITIND","PIIND","PILANIINVS","PILITA","PIONEEREMB","PITTIENG","PIXTRANS","PKTEA","PLASTIBLEN","PNB","PNB-RE","PNBGILTS","PNBHOUSING","PNC","PNCINFRA","POCL","PODDARHOUS","PODDARMENT","POKARNA","POLICYBZR","POLYCAB","POLYMED","POLYPLEX","PONNIERODE","POONAWALLA","POWERGRID","POWERINDIA","POWERMECH","PPAP","PPL","PPLPHARMA","PRAENG","PRAJIND","PRAKASH","PRAKASHSTL","PRAXIS","PRECAM","PRECOT","PRECWIRE","PREMEXPLN","PREMIER","PREMIERPOL","PRESSMN","PRESTIGE","PRICOLLTD","PRIMESECU","PRINCEPIPE","PRITI","PRITIKAUTO","PRIVISCL","PROZONINTU","PRSMJOHNSN","PRUDENT","PSB","PSPPROJECT","PTC","PTL","PUNJABCHEM","PURVA","PVP","PVR","QUESS","QUICKHEAL","RADHIKAJWE","RADIANTCMS","RADICO","RADIOCITY","RAILTEL","RAIN","RAINBOW","RAJESHEXPO","RAJMET","RAJRATAN","RAJRILTD","RAJSREESUG","RAJTV","RALLIS","RAMANEWS","RAMAPHO","RAMASTEEL","RAMCOCEM","RAMCOIND","RAMCOSYS","RAMKY","RAMRAT","RANASUG","RANEENGINE","RANEHOLDIN","RATEGAIN","RATNAMANI","RAYMOND","RBA","RBL","RBLBANK","RCF","RECLTD","REDINGTON","REFEX","REGENCERAM","RELAXO","RELCAPITAL","RELCHEMQ","RELIANCE","RELIGARE","RELINFRA","REMSONSIND","RENUKA","REPCOHOME","REPL","REPRO","RESPONIND","REVATHI","RGL","RHFL","RHIM","RICOAUTO","RIIL","RITCO","RITES","RKDL","RKEC","RKFORGE","RMCL","RML","RNAVAL","ROHLTD","ROLEXRINGS","ROLLT","ROML","ROSSARI","ROSSELLIND","ROTO","ROUTE","RPGLIFE","RPOWER","RPPINFRA","RPPL","RPSGVENT","RSSOFTWARE","RSWM","RSYSTEMS","RTNINDIA","RTNPOWER","RUBYMILLS","RUCHINFRA","RUCHIRA","RUPA","RUSHIL","RUSTOMJEE","RVHL","RVNL","S&SPOWER","SABEVENTS","SABTN","SADBHAV","SADBHIN","SAFARI","SAGARDEEP","SAGCEM","SAH","SAHYADRI","SAIL","SAKAR","SAKHTISUG","SAKSOFT","SAKUMA","SALASAR","SALONA","SALSTEEL","SALZERELEC","SAMBHAAV","SANCO","SANDESH","SANDHAR","SANGAMIND","SANGHIIND","SANGHVIMOV","SANGINITA","SANOFI","SANSERA","SAPPHIRE","SARDAEN","SAREGAMA","SARLAPOLY","SARVESHWAR","SASKEN","SASTASUNDR","SATIA","SATIN","SATINDLTD","SBC","SBCL","SBGLP","SBICARD","SBILIFE","SBIN","SCAPDVR","SCHAEFFLER","SCHAND","SCHNEIDER","SCI","SCPL","SDBL","SEAMECLTD","SECURCRED","SECURKLOUD","SEJALLTD","SELAN","SELMC","SEPC","SEPOWER","SEQUENT","SERVOTECH","SESHAPAPER","SETCO","SEYAIND","SFL","SGIL","SGL","SHAHALLOYS","SHAILY","SHAKTIPUMP","SHALBY","SHALPAINTS","SHANKARA","SHANTI","SHANTIGEAR","SHARDACROP","SHARDAMOTR","SHAREINDIA","SHEMAROO","SHILPAMED","SHIVALIK","SHIVAMAUTO","SHIVAMILLS","SHIVATEX","SHK","SHOPERSTOP","SHRADHA","SHREDIGCEM","SHREECEM","SHREEPUSHK","SHREERAMA","SHRENIK","SHREYANIND","SHREYAS","SHRIPISTON","SHRIRAMFIN","SHRIRAMPPS","SHYAMCENT","SHYAMMETL","SHYAMTEL","SIEMENS","SIGACHI","SIGIND","SIKKO","SIL","SILGO","SILINV","SILLYMONKS","SILVERTUC","SIMBHALS","SIMPLEXINF","SINTERCOM","SIRCA","SIS","SITINET","SIYSIL","SJS","SJVN","SKFINDIA","SKIPPER","SKMEGGPROD","SKYGOLD","SMARTLINK","SMCGLOBAL","SMLISUZU","SMLT","SMSLIFE","SMSPHARMA","SNOWMAN","SOBHA","SOFTTECH","SOLARA","SOLARINDS","SOMANYCERA","SOMATEX","SOMICONVEY","SONACOMS","SONAMCLOCK","SONATSOFTW","SOTL","SOUTHBANK","SOUTHWEST","SPAL","SPANDANA","SPARC","SPCENET","SPECIALITY","SPENCERS","SPENTEX","SPIC","SPICEJET","SPLIL","SPLPETRO","SPMLINFRA","SPORTKING","SREEL","SRF","SRHHYPOLTD","SRPL","SSWL","STAR","STARCEMENT","STARHEALTH","STARPAPER","STARTECK","STCINDIA","STEELCAS","STEELCITY","STEELXIND","STEL","STERTOOLS","STLTECH","STOVEKRAFT","STYLAMIND","STYRENIX","SUBEXLTD","SUBROS","SUDARSCHEM","SUKHJITS","SULA","SUMEETINDS","SUMICHEM","SUMIT","SUMMITSEC","SUNCLAYLTD","SUNDARAM","SUNDARMFIN","SUNDARMHLD","SUNDRMBRAK","SUNDRMFAST","SUNFLAG","SUNPHARMA","SUNTECK","SUNTV","SUPERHOUSE","SUPERSPIN","SUPRAJIT","SUPREMEENG","SUPREMEIND","SUPREMEINF","SUPRIYA","SURANASOL","SURANAT&P","SURYALAXMI","SURYAROSNI","SURYODAY","SUTLEJTEX","SUULD","SUVEN","SUVENPHAR","SUVIDHAA","SUZLON","SVLL","SVPGLOB","SWANENERGY","SWARAJENG","SWELECTES","SWSOLAR","SYMPHONY","SYNCOMF","SYNGENE","SYRMA","TAINWALCHM","TAJGVK","TAKE","TALBROAUTO","TANLA","TANTIACONS","TARAPUR","TARC","TARMAT","TARSONS","TASTYBITE","TATACHEM","TATACOFFEE","TATACOMM","TATACONSUM","TATAELXSI","TATAINVEST","TATAMETALI","TATAMOTORS","TATAMTRDVR","TATAPOWER","TATASTEEL","TATASTLLP","TATVA","TBZ","TCI","TCIEXP","TCNSBRANDS","TCPLPACK","TCS","TDPOWERSYS","TEAMLEASE","TECHIN","TECHM","TECHNOE","TECILCHEM","TEGA","TEJASNET","TEMBO","TERASOFT","TEXINFRA","TEXMOPIPES","TEXRAIL","TFCILTD","TFL","TGBHOTELS","THANGAMAYL","THEINVEST","THEMISMED","THERMAX","THOMASCOOK","THOMASCOTT","THYROCARE","TI","TIDEWATER","TIIL","TIINDIA","TIJARIA","TIL","TIMESGTY","TIMETECHNO","TIMKEN","TINPLATE","TIPSFILMS","TIPSINDLTD","TIRUMALCHM","TIRUPATIFL","TITAN","TMB","TNPETRO","TNPL","TNTELE","TOKYOPLAST","TORNTPHARM","TORNTPOWER","TOTAL","TOUCHWOOD","TPLPLASTEH","TRACXN","TREEHOUSE","TREJHARA","TRENT","TRF","TRIDENT","TRIGYN","TRIL","TRITURBINE","TRIVENI","TRU","TTKHLTCARE","TTKPRESTIG","TTL","TTML","TV18BRDCST","TVSELECT","TVSMOTOR","TVSSRICHAK","TVTODAY","TVVISION","TWL","UBL","UCALFUEL","UCOBANK","UDAICEMENT","UFLEX","UFO","UGARSUGAR","UGROCAP","UJAAS","UJJIVAN","UJJIVANSFB","ULTRACEMCO","UMAEXPORTS","UMANGDAIRY","UMESLTD","UNICHEMLAB","UNIDT","UNIENTER","UNIINFO","UNIONBANK","UNIPARTS","UNITECH","UNITEDPOLY","UNITEDTEA","UNIVASTU","UNIVCABLES","UNIVPHOTO","UNOMINDA","UPL","URJA","USHAMART","USK","UTIAMC","UTTAMSUGAR","V2RETAIL","VADILALIND","VAIBHAVGBL","VAISHALI","VAKRANGEE","VALIANTORG","VARDHACRLC","VARDMNPOLY","VARROC","VASCONEQ","VASWANI","VBL","VCL","VEDL","VENKEYS","VENUSPIPES","VENUSREM","VERANDA","VERTOZ","VESUVIUS","VETO","VGUARD","VHL","VICEROY","VIDHIING","VIJAYA","VIJIFIN","VIKASECO","VIKASLIFE","VIKASWSP","VIMTALABS","VINATIORGA","VINDHYATEL","VINEETLAB","VINNY","VINYLINDIA","VIPCLOTHNG","VIPIND","VIPULLTD","VISAKAIND","VISASTEEL","VISESHINFO","VISHAL","VISHNU","VISHWARAJ","VIVIDHA","VLSFINANCE","VMART","VOLTAMP","VOLTAS","VRLLOG","VSSL","VSTIND","VSTTILLERS","VTL","WABAG","WALCHANNAG","WANBURY","WATERBASE","WEALTH","WEBELSOLAR","WEIZMANIND","WEL","WELCORP","WELENT","WELINV","WELSPUNIND","WENDT","WESTLIFE","WEWIN","WHEELS","WHIRLPOOL","WILLAMAGOR","WINDLAS","WINDMACHIN","WINPRO","WIPL","WIPRO","WOCKPHARMA","WONDERLA","WORTH","WSI","WSTCSTPAPR","XCHANGING","XELPMOC","XPROINDIA","YAARI","YESBANK","YUKEN","ZEEL","ZEELEARN","ZEEMEDIA","ZENITHEXPO","ZENITHSTL","ZENSARTECH","ZENTEC","ZFCVINDIA","ZIMLAB","ZODIAC","ZODIACLOTH","ZOMATO","ZOTA","ZUARI","ZUARIIND","ZYDUSLIFE","ZYDUSWELL"]
trading_dates_list = [i[0] for i in fetch_data(f"select date from daily_nifty  WHERE MONTH(date) in ('01','02','03','04','05','06','07','08','09','10','11','12') AND YEAR(date) in ('2023');")]
# print (trading_dates_list)
# exit(0)
# symbol_data = ["WONDERLA"]
# trading_dates_list = [datetime(2023,4,21)]


# print (trading_dates_list)
if __name__ == "__main__":
    for symbol_data2 in list(chunks(symbol_data, 1000)):
        x1 = multiprocessing.Process(target=process_start,args=(trading_dates_list,symbol_data2,))
        x1.start()


